In [11]:
# The goal of this notebook is to figure out how to make a copy layer

import numpy as np
from keras import backend as K
from keras.models import Model
from keras.layers import Input, Dense, Flatten, Reshape, UpSampling3D


In [12]:
n_channels = 3
im_height = 5
im_width = 5

n_rep = 2

In [13]:
input_layer = Input(shape = (1,im_height, im_width,n_channels))
output_layer = UpSampling3D(size=(n_rep,1,1))(input_layer)

my_model = Model(inputs = input_layer, outputs = output_layer)

In [18]:
test_data = np.ones(shape = (1,im_height,im_width,n_channels))

In [22]:
batched_test_data = np.expand_dims(test_data,axis = 0)

In [23]:
batched_test_data.shape

(1, 1, 5, 5, 3)

In [25]:
out_test = my_model.predict(batched_test_data)

In [26]:
out_test.shape

(1, 2, 5, 5, 3)

In [36]:
new_test = np.random.normal(size = (1,im_height,im_width,n_channels))

In [37]:
new_batched_test = np.expand_dims(new_test,axis = 0)

In [38]:
real_test = my_model.predict(new_batched_test)

In [39]:
real_test.shape

(1, 2, 5, 5, 3)

In [40]:
new_batched_test.shape

(1, 1, 5, 5, 3)

In [41]:
new_batched_test

array([[[[[-0.0334921 ,  1.24122522, -0.8239137 ],
          [ 0.77127855, -0.71984875, -0.11075273],
          [ 0.13564072,  1.56946612,  1.57202644],
          [-0.08771299, -0.26529496,  0.75061859],
          [ 1.34339893,  1.23866724,  0.92301009]],

         [[-0.75403848,  1.24639244, -0.06478041],
          [-0.12423375, -0.2655426 , -0.6009753 ],
          [ 1.01444138, -0.21644387,  0.6885904 ],
          [-0.24498028, -1.98968674, -1.21269282],
          [-1.33622834, -1.86573731, -0.67121718]],

         [[ 1.04124036, -0.72212924,  0.46008672],
          [-0.95356087, -0.28742913,  0.19534648],
          [ 0.37373382,  1.55271244,  0.40990626],
          [-0.22377924,  0.59257788,  0.88753593],
          [ 0.18706544, -1.1466984 , -0.80474711]],

         [[ 0.15470138, -1.5597559 , -0.63841445],
          [-0.88345786, -0.87879459,  0.72003996],
          [ 0.84902754, -3.43563199,  0.3547264 ],
          [-1.72243831, -0.71979967,  0.61287186],
          [ 0.0259125 ,  

In [42]:
real_test[:,0,:,:,:]

array([[[[-0.0334921 ,  1.2412252 , -0.8239137 ],
         [ 0.77127856, -0.71984875, -0.11075273],
         [ 0.13564073,  1.5694661 ,  1.5720265 ],
         [-0.087713  , -0.26529497,  0.7506186 ],
         [ 1.3433989 ,  1.2386672 ,  0.9230101 ]],

        [[-0.7540385 ,  1.2463925 , -0.06478041],
         [-0.12423375, -0.2655426 , -0.6009753 ],
         [ 1.0144414 , -0.21644387,  0.6885904 ],
         [-0.24498028, -1.9896867 , -1.2126929 ],
         [-1.3362284 , -1.8657373 , -0.6712172 ]],

        [[ 1.0412403 , -0.7221292 ,  0.46008673],
         [-0.9535609 , -0.28742912,  0.19534647],
         [ 0.37373382,  1.5527124 ,  0.40990627],
         [-0.22377925,  0.5925779 ,  0.8875359 ],
         [ 0.18706544, -1.1466984 , -0.8047471 ]],

        [[ 0.15470138, -1.5597559 , -0.63841444],
         [-0.88345784, -0.8787946 ,  0.72003996],
         [ 0.8490275 , -3.435632  ,  0.3547264 ],
         [-1.7224383 , -0.7197997 ,  0.6128719 ],
         [ 0.0259125 ,  0.05291405,  0.53269

In [43]:
real_test[:,1,:,:,:]

array([[[[-0.0334921 ,  1.2412252 , -0.8239137 ],
         [ 0.77127856, -0.71984875, -0.11075273],
         [ 0.13564073,  1.5694661 ,  1.5720265 ],
         [-0.087713  , -0.26529497,  0.7506186 ],
         [ 1.3433989 ,  1.2386672 ,  0.9230101 ]],

        [[-0.7540385 ,  1.2463925 , -0.06478041],
         [-0.12423375, -0.2655426 , -0.6009753 ],
         [ 1.0144414 , -0.21644387,  0.6885904 ],
         [-0.24498028, -1.9896867 , -1.2126929 ],
         [-1.3362284 , -1.8657373 , -0.6712172 ]],

        [[ 1.0412403 , -0.7221292 ,  0.46008673],
         [-0.9535609 , -0.28742912,  0.19534647],
         [ 0.37373382,  1.5527124 ,  0.40990627],
         [-0.22377925,  0.5925779 ,  0.8875359 ],
         [ 0.18706544, -1.1466984 , -0.8047471 ]],

        [[ 0.15470138, -1.5597559 , -0.63841444],
         [-0.88345784, -0.8787946 ,  0.72003996],
         [ 0.8490275 , -3.435632  ,  0.3547264 ],
         [-1.7224383 , -0.7197997 ,  0.6128719 ],
         [ 0.0259125 ,  0.05291405,  0.53269